config/routes.rb
Rails.application.routes.draw do
  # get 'pages/About_us'
  # get 'pages/faq'
  # get 'pages/Social_Relation'
  # get 'home/index'
  
  root "home#index"
  get '/faq' => 'pages#faq'
  get '/social-relation' => 'pages#Social_Relation'
  get '/about' => 'pages#About_us'
  get '/contact' => 'form_page#Contact_us'
  # get 'form_page/Contact_us'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/form_page_controller.rb
class FormPageController < ApplicationController
  def Contact_us
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def About_us
  end

  def faq
  end

  def Social_Relation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_page_helper.rb
module FormPageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/form_page/Contact_us.html.erb
<%= stylesheet_link_tag "contact" %>

<div class="contact">
    <div class="contactContent">
        <div class="info">

            <div class="heading">
                <h3>Contact Us</h3>
            </div>
            <div class="contact_info">
                <div class="phone"><i class="bi bi-telephone-fill"></i>7375838577</div>
                <div class="mail_me"><i class="bi bi-envelope-fill"></i>zuluzulu173@gmail.com</div>
                <div class="mylocation"><i class="bi bi-geo-alt-fill"></i>1234 Near Gandhi Market, Alwar 301001 Rajasthan</div>
            </div>
            
            </div>


            <form action="">
                    <div class="form_fld">
                        <label for="">First Name</label>
                        <input type="text">
                        <label for="">Last Name</label>
                        <input type="text">
                        <label for="">Email</label>
                        <input type="email">
                        <label for="">company</label>
                        <input type="text">
                        <label for="">Message</label>
                        <textarea name=""></textarea>
                        <div class="submit_button">
                            <div class="btn">Submit</div>
                        </div>

                    </div>

            </form>
        </div>

    </div>

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZOITW</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'partials/nav' %>
  <div class="main_render">
    <%= yield %>


  </div>
    <%= render 'partials/footer' %>
    
  </body>
</html>

app/views/pages/About_us.html.erb
<%= stylesheet_link_tag "index" %>

<div class="home_greetings">
    <div class="content">
        <h2>A little bit</h2>
        <h1>About us</h1>
    </div>
</div>

<div class="who_we_are">
    <div class="sub_heading">
        <h3>WHO WE ARE</h3>
    </div>
    <div class="content">
        <p>FOUNDED IN 2020 IN  ALWAR, ZOITW IS AN IT COMPANY THAT STARTED AS A SMALL TEAM OF 5 TALENTED INDIVIDUALS AND HAS NOW GROWN INTO A NEITHER-TOO-BIG NOR TOO-SMALL COMPANY THAT PROVIDES CUSTOM-TAILORED PRODUCTS TO FUEL YOUR BUSINESS GROWTH.</p>
    </div>
</div>


<div class="sectorsWeServe">
    <div class="zoitw_text">
        ZOITW
    </div>

    <div class="sectorContent">
        <div class="secondary_heading">
            <h3>WHO WE ARE</h3>
        </div>

    </div>

</div> 

<div class="careers">
    <div class="main_heading">
        <h3>Careers</h3>
    </div>
    <p>We provide tailored services for businesses to succeed in the digital landscape.</p>
<div id="carouselExampleControlsNoTouching" class="carousel slide" data-bs-touch="false">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="careers_options_desktop">
        <div class="items">
            <div class="box">
                <%= image_tag 'index/CareerSlider/3D Modeling.png', :class => "careers_logo" %>
                <div class="text">3D Modeling</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Analyst.png', :class => "careers_logo" %>
                <div class="text">Analyst</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Animation.png', :class => "careers_logo" %>
                <div class="text">Animation</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Devops.png', :class => "careers_logo" %>
                <div class="text">Devops</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Digital Marketing.png', :class => "careers_logo" %>
                <div class="text">Digital Marketing</div>
            </div>
        </div>
        <div class="items ">
            <div class="box">
                <%= image_tag 'index/CareerSlider/Doodling.png', :class => "careers_logo" %>
                <div class="text">Doodling</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Editing.png', :class => "careers_logo" %>
                <div class="text">Editing</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Electrical Engineering.png', :class => "careers_logo" %>
                <div class="text">Electrical Engineering</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Electronics Engineering.png', :class => "careers_logo" %>
                <div class="text">Electronics Engineering</div>
            </div>
        </div>
        <div class="items ">
            <div class="box">
                <%= image_tag 'index/CareerSlider/Environmentalist.png', :class => "careers_logo" %>
                <div class="text">Environmentalist</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Graphic Designing.png', :class => "careers_logo" %>
                <div class="text">Graphic Designing</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Human Resource.png', :class => "careers_logo" %>
                <div class="text">Human Resource</div>
            </div>
        </div>


    </div>
    </div>
    <div class="carousel-item">
     <div class="careers_options_desktop">
        <div class="items">
            <div class="box">
                <%= image_tag 'index/CareerSlider/IOT.png', :class => "careers_logo" %>
                <div class="text">IOT</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/AI.png', :class => "careers_logo" %>
                <div class="text">AI</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Mechanical Engineering.png', :class => "careers_logo" %>
                <div class="text">Mechanical Engineering</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Mobile Application Development.png', :class => "careers_logo" %>
                <div class="text">Mobile Application Development</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Network Administrator.png', :class => "careers_logo" %>
                <div class="text">Network Administrator</div>
            </div>
        </div>
        <div class="items ">
            <div class="box">
                <%= image_tag 'index/CareerSlider/Operation Manager.png', :class => "careers_logo" %>
                <div class="text">Operation Manager</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Photography.png', :class => "careers_logo" %>
                <div class="text">Photography</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Robotics.png', :class => "careers_logo" %>
                <div class="text">Robotics</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Sales and Marketing.png', :class => "careers_logo" %>
                <div class="text">Sales and Marketing</div>
            </div>
        </div>
        <div class="items ">
            <div class="box">
                <%= image_tag 'index/CareerSlider/Sales and Marketing.png', :class => "careers_logo" %>
                <div class="text">Sales and Marketing</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/UX.png', :class => "careers_logo" %>
                <div class="text">UX</div>
            </div>
            <div class="box">
                <%= image_tag 'index/CareerSlider/Web Development.png', :class => "careers_logo" %>
                <div class="text">Web Development</div>
            </div>
        </div>


    </div>
    </div>
   
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
    <span aria-hidden="true">
        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='#FB9400'>
            <path d='M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z'/>
        </svg>
    </span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
    <span  aria-hidden="true">
        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='#FB9400'>
            <path d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/>
        </svg>
    </span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
    



</div>

<div class="MissionVision">
    <div class="zoitw_text">
        ZOITW
    </div>

    <div class="missionVisionContent">
        <div class="head_content">
            <div class="secondary_heading">
                <h3>Our <br> Mission And <br> Vision</h3>
            </div>
            <p>Creating a business application, ERP application, automation solution or boosting the business via digital marketing; we work with one definite approach & ideology of 3DP.</p>
            <ul>
                <li>Determination</li>
                <li>Dedication</li>
                <li>Discipline</li>
                <li>Perseverance</li>
            </ul>

        </div>
        <div class="content">
            <div class="mission">
            <%= image_tag 'index/topLeft.png' , :class => "topLeft " %>
            <%= image_tag 'index/topRight.png' , :class => "topRight " %>
            <%= image_tag 'index/bottomLeft.png' , :class => "bottomLeft " %>
            <%= image_tag 'index/bottomRight.png' , :class => "bottomRight " %>
            <div class="sub_heading">
                <h3>Mission</h3>
            </div>
            <p>
                Our mission is to cater to diverse market segments by delivering pioneering solutions that address their specific challenges through the integration of state-of-the-art technology. Our aim is to streamline operational costs and enhance efficiency, resulting in improved product value. With a steadfast commitment to staying ahead in the market, we prioritize the adoption of cutting-edge technologies that empower our business to maintain a competitive edge. We place significant emphasis on comprehending our clients' unique requirements, enabling us to provide innovative solutions that effectively address their opportunities and challenges. Throughout this process, we strive to deliver exceptional customer service, ensuring utmost satisfaction.
            </p>
            
                
            </div>
            <div class="vision">
            <%= image_tag 'index/topLeft.png' , :class => "topLeft " %>
            <%= image_tag 'index/topRight.png' , :class => "topRight " %>
            <%= image_tag 'index/bottomLeft.png' , :class => "bottomLeft " %>
            <%= image_tag 'index/bottomRight.png' , :class => "bottomRight " %>
            <div class="sub_heading">
                <h3>Vision</h3>
            </div>
            <p>
            Our vision is to enhance and uplift our environment in a manner that fosters a high regard for human life, leveraging cutting-edge technology. We aim to establish ourselves as a reliable and valued partner for organizations seeking to revolutionize their operations and excel in an ever-evolving technological landscape. Our core values encompass excellence, integrity, quality, and customer satisfaction, driving our commitment to achieving unparalleled results. Through our adaptability to emerging technologies, we aspire to shape the world by addressing global challenges and elevating the standard of living through innovative solutions.   
            </p>
            
                
            </div>

        </div>

    </div>

</div> 

<div class="ourSubsidiaries">
    <div class="main_heading">
        <h3>Our Subsidiaries</h3>
    </div>
    <div class="Subsidiaries_container max_w">

        <div class="SubsidiariesContent_text">

            <div class="Subsidiaries_text">
                <div class="name  zits_subsidiaries "><h2>ZULUITSOLUTIONS</h2></div>
                <div class="date">2019 / BRAND IDENTITY / WEB</div>
                <p>Zits is an IT company that provides solutions for etc etc etc etc and a little more description Zits is an IT company that provides solutions for etc etc etc etc and a little more description </p>
            </div>

            <div class="Subsidiaries_img">
                <%= image_tag 'index/sub1.png', :class => "subsidiaries_img1" %>
            </div>

        </div>
        <div class="SubsidiariesContent_text">

            <div class="Subsidiaries_img">
                <%= image_tag 'index/sub1.png', :class => "subsidiaries_img1" %>
            </div>
            <div class="Subsidiaries_text">

            </div>


        </div>
    </div>
</div>

app/views/pages/faq.html.erb
<%= stylesheet_link_tag "faq" %>

<div class="faq">
    <%# <div class="zoitw_text">
        ZOITW
    </div> %>

    <div class="faqContent">
        <div class="heading">
            <h3>FAQ</h3>
        </div>
         <section id="FAQ">
            <div class="img_section"><img src="img/app/FAQ.png" alt=""></div>

            <div class="content">
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Quisque rutrum. Aenean sa  im perdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget. asd sd d s we 
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                               Quisque rutrum. Aenean imperdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Quisque rutrum. Aenean imperdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget.
                            </div>
                        </div>
                    </div>

                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFour">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapsgFour" aria-expanded="false" aria-controls="collapsgFour">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapsgFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Quisque rutrum. Aenean imperdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget.
                            </div>
                        </div>
                    </div>

                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFive">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Quisque rutrum. Aenean imperdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingSix">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                Can I choose my meals?
                            </button>
                        </h2>
                        <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                Quisque rutrum. Aenean imperdi. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget.
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </div>

</div> 

app/views/partials/_nav.html.erb
<%= stylesheet_link_tag "nav" %>


<nav class="navbar navbar-expand-lg">
  <div class="container">
    <%= link_to root_path do %>
    <%= image_tag "ZOITW.png", alt: "Logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to  "Home", "/", :class =>  "nav-link #{'active' if current_page?(root_path)}" %>
            <div class="othernav_link">
              <i class="bi bi-chevron-up"></i>
              <div class="content">
                <div class="nav_content">
                  <div class="page_link_group">
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
        </li>
        <li class="nav-item">
            <%= link_to "About Us", about_path, class: "nav-link #{'active' if current_page?(about_path)}" %>
          <div class="othernav_link">
              <i class="bi bi-chevron-up"></i>
              <div class="content">
                <div class="nav_content">
                  <div class="page_link_group">
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about </h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </li>
         <li class="nav-item">
            <%= link_to "Social Relation", social_relation_path, class: "nav-link #{'active' if current_page?(social_relation_path)}" %>
            <div class="othernav_link">
              <i class="bi bi-chevron-up"></i>
              <div class="content">
                <div class="nav_content">
                  <div class="page_link_group">
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </li>
         <li class="nav-item">
            <%= link_to "FAQ", faq_path, class: "nav-link #{'active' if current_page?(faq_path)}" %>
            <div class="othernav_link">
              <i class="bi bi-chevron-up"></i>
              <div class="content">
                <div class="nav_content">
                  <div class="page_link_group">
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                    <div class="link">
                      <div class="col_1">
                      <i class="bi bi-file-bar-graph"></i>
                      </div>
                      <div class="col_2">
                      <%= link_to  "Sectors We Serve", "/" , :class => "page_link" %>
                      <h6>Learn about Lorem Ipsum</h6>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </li>
      </ul>
        <%= link_to "Contact Us", contact_path, class: "main_btn #{'active' if current_page?(contact_path)}" %>
    </div>
  </div>
</nav>